from ARMOR          import ARMOR
from CHARACTERS     import CHARACTERS
from COLLISIONS     import COLLISIONS
from FLAGS          import FLAGS
from GOODS          import GOODS
from ITEMLOTS       import ITEMLOTS
from RINGS          import RINGS
from SPECIALEFFECTS import SPECIALEFFECTS
from TEXT           import TEXT
from VISUALEFFECTS  import VISUALEFFECTS
from WEAPONS        import WEAPONS
